//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAssignmentTask2_Web.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ISimpleCalculator")]
    public interface ISimpleCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Add", ReplyAction="http://tempuri.org/ISimpleCalculator/AddResponse")]
        double Add(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Add", ReplyAction="http://tempuri.org/ISimpleCalculator/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Subtract", ReplyAction="http://tempuri.org/ISimpleCalculator/SubtractResponse")]
        double Subtract(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Subtract", ReplyAction="http://tempuri.org/ISimpleCalculator/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Multiply", ReplyAction="http://tempuri.org/ISimpleCalculator/MultiplyResponse")]
        double Multiply(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Multiply", ReplyAction="http://tempuri.org/ISimpleCalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Divide", ReplyAction="http://tempuri.org/ISimpleCalculator/DivideResponse")]
        double Divide(double dblNum1, double dblNum2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleCalculator/Divide", ReplyAction="http://tempuri.org/ISimpleCalculator/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double dblNum1, double dblNum2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleCalculatorChannel : WCFAssignmentTask2_Web.ServiceReference2.ISimpleCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleCalculatorClient : System.ServiceModel.ClientBase<WCFAssignmentTask2_Web.ServiceReference2.ISimpleCalculator>, WCFAssignmentTask2_Web.ServiceReference2.ISimpleCalculator {
        
        public SimpleCalculatorClient() {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double dblNum1, double dblNum2) {
            return base.Channel.Add(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double dblNum1, double dblNum2) {
            return base.Channel.AddAsync(dblNum1, dblNum2);
        }
        
        public double Subtract(double dblNum1, double dblNum2) {
            return base.Channel.Subtract(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double dblNum1, double dblNum2) {
            return base.Channel.SubtractAsync(dblNum1, dblNum2);
        }
        
        public double Multiply(double dblNum1, double dblNum2) {
            return base.Channel.Multiply(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double dblNum1, double dblNum2) {
            return base.Channel.MultiplyAsync(dblNum1, dblNum2);
        }
        
        public double Divide(double dblNum1, double dblNum2) {
            return base.Channel.Divide(dblNum1, dblNum2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double dblNum1, double dblNum2) {
            return base.Channel.DivideAsync(dblNum1, dblNum2);
        }
    }
}
