//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20_MVC_Assignment_1_DOTNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.TWEETs = new HashSet<TWEET>();
            this.Person1 = new HashSet<Person>();
            this.People = new HashSet<Person>();
        }
    
        public string user_id { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public System.DateTime joined { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<TWEET> TWEETs { get; set; }
        public virtual ICollection<Person> Person1 { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
