//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8784
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITask1")]
public interface ITask1
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask1/SayHello", ReplyAction="http://tempuri.org/ITask1/SayHelloResponse")]
    string SayHello(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask1/TodayProgram", ReplyAction="http://tempuri.org/ITask1/TodayProgramResponse")]
    string TodayProgram(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ITask1Channel : ITask1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Task1Client : System.ServiceModel.ClientBase<ITask1>, ITask1
{
    
    public Task1Client()
    {
    }
    
    public Task1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Task1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Task1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Task1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SayHello(string name)
    {
        return base.Channel.SayHello(name);
    }
    
    public string TodayProgram(string name)
    {
        return base.Channel.TodayProgram(name);
    }
}
