//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAssignmentTask2_Web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITask2")]
    public interface ITask2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask2/OpeningJobs", ReplyAction="http://tempuri.org/ITask2/OpeningJobsResponse")]
        string[] OpeningJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask2/OpeningJobs", ReplyAction="http://tempuri.org/ITask2/OpeningJobsResponse")]
        System.Threading.Tasks.Task<string[]> OpeningJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask2/OpeningJobsByRole", ReplyAction="http://tempuri.org/ITask2/OpeningJobsByRoleResponse")]
        string[] OpeningJobsByRole(string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITask2/OpeningJobsByRole", ReplyAction="http://tempuri.org/ITask2/OpeningJobsByRoleResponse")]
        System.Threading.Tasks.Task<string[]> OpeningJobsByRoleAsync(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITask2Channel : WCFAssignmentTask2_Web.ServiceReference1.ITask2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Task2Client : System.ServiceModel.ClientBase<WCFAssignmentTask2_Web.ServiceReference1.ITask2>, WCFAssignmentTask2_Web.ServiceReference1.ITask2 {
        
        public Task2Client() {
        }
        
        public Task2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Task2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Task2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Task2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] OpeningJobs() {
            return base.Channel.OpeningJobs();
        }
        
        public System.Threading.Tasks.Task<string[]> OpeningJobsAsync() {
            return base.Channel.OpeningJobsAsync();
        }
        
        public string[] OpeningJobsByRole(string role) {
            return base.Channel.OpeningJobsByRole(role);
        }
        
        public System.Threading.Tasks.Task<string[]> OpeningJobsByRoleAsync(string role) {
            return base.Channel.OpeningJobsByRoleAsync(role);
        }
    }
}
